### ISSUE TITLE
How to disable ssl verification?

### ISSUE THREAD

**Issue by hamidreza2005** [Jeroen-G/Explorer#61]
Hi there 
i am using elasticsearch on docker.
here is my docker-compose.yml
```yml
    other containers ...
    elastic01:
        image: elasticsearch:7.13.4
        container_name: elastic01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./docker/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9201:9200
        networks:
            - app
            - elastic
```
i have configured laravel scout and this package as just documentation
and i have imported model's data by running
```shell
php artisan scout:import \App\Models\Post
```
but when i try to search in models or run `php artisan elastic:create `  i get this error
```shell
   Elasticsearch\Common\Exceptions\NoNodesAvailableException 

  No alive nodes found in your cluster

  at vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:64
     60▕                 return $connection;
     61▕             }
     62▕         }
     63▕ 
  ➜  64▕         throw new NoNodesAvailableException("No alive nodes found in your cluster");
     65▕     }
     66▕ 
     67▕     public function scheduleCheck(): void
     68▕     {

      +26 vendor frames 
  27  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
ERROR: 1

```

i searched this error in google and i realized that i have to disable ssl verification . how can i do that?
